service: serverless-evnt-sub 
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/posts"

functions:
  createPost:
    handler: handler.createPost
    events:
      - eventBridge:
          pattern:
            source:
              - codurance.event2 
